<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Logout</name>
   <tag></tag>
   <elementGuidId>110a2056-90b2-4604-8250-d277844f67f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/aside/ul/div[15]/li/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(15) > li > a > div.sidebar_menuItem__3mWxl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Logout&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2d621057-43d8-4a61-a461-d217f1f0327c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar_menuItem__3mWxl</value>
      <webElementGuid>29b5da6f-36d9-414b-8573-dfd39cb792bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7a8f617-ee07-4f49-b575-9957ac96e703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>82c09af8-fdd5-4430-9cab-e7dc58ba4ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout__tZtl7&quot;]/aside[@class=&quot;sidebar_sidebar___sE6K&quot;]/ul[@class=&quot;sidebar_menu__2b3Rz&quot;]/div[15]/li[1]/a[1]/div[@class=&quot;sidebar_menuItem__3mWxl&quot;]</value>
      <webElementGuid>891a9f01-dd45-40a7-8cc2-1f5197b331b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/aside/ul/div[15]/li/a/div</value>
      <webElementGuid>42f0db24-06df-469f-bd94-f69a40d8d520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile'])[1]/following::div[2]</value>
      <webElementGuid>e14266e1-c54e-450e-b469-1d7750b6c3ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checker Operations'])[1]/following::div[4]</value>
      <webElementGuid>0235ae7b-2ba8-4fda-be65-f18e2c37d042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-Para Backoffice'])[2]/preceding::div[2]</value>
      <webElementGuid>e9f92f69-6dec-4e64-8291-91f77ba6d2d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='🇬🇧 English'])[1]/preceding::div[3]</value>
      <webElementGuid>c26b9a7c-1483-4c49-945c-2b708342eb63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>09935df9-7bab-4500-955f-0ae7bec48bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/li/a/div</value>
      <webElementGuid>33f31886-6194-4d58-8a49-90ec9494221c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>6bdfeb6e-615d-41d2-8ca2-c961178741d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
