
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile2'
    tags: |
      $(Build.BuildId)

