
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile2'
    tags: |
      $(Build.BuildId)
- script: |
    docker run -t --rm -v ${pwd}:/tmp/project docker.io/bktpay/katalon-test:$(Build.BuildId) katalonc.sh -projectPath=/tmp/project -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTestCollection"  -apiKey="554d7f82-ac15-4b60-aab3-739c97658f70" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true 
  displayName: 'Run Android emulator in Docker container'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
