
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile2'
    tags: |
      $(Build.BuildId)
- script: |
    docker run -t --name android_emulator -v $(System.DefaultWorkingDirectory):/workspace docker.io/bktpay/katalon-test:$(Build.BuildId)
  displayName: 'Run Android emulator in Docker container'
