trigger:
  - master

jobs:
  - job: ubuntu
    pool:
      vmImage: ubuntu-latest
      name: BKTPAY UAT Agents

    steps:
    

       - script: |
          sudo apt-get update
          sudo apt install openjdk-17-jdk openjdk-17-jre
          curl -O https://download.katalon.com/9.6.0/Katalon_Studio_Engine_Linux_64-9.6.0.tar.gz
          tar -xzf Katalon_Studio_Engine_Linux_64-9.6.0.tar.gz
          cd Katalon_Studio_Engine_Linux_64-9.6.0
          ls
          chmod +x katalonc
          ./katalonc -noSplash -runMode=console  -retry=0 -projectPath="/Users/runner/work/1/s" -testSuitePath="Test Suites/Test_Suite_Web" -browserType="Chrome" -executionProfile="default" -apiKey="f3ab2f6b-d373-4618-b87c-7471b31a5506" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true -appiumDirectory="/Users/runner/work/1/s/node_modules/appium"
          ./katalonc
