trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run -d --name android_emulator -v $(System.DefaultWorkingDirectory):/workspace katalon-test:$(Build.BuildId)
  displayName: 'Run Android emulator in Docker container'

- script: |
    docker exec android_emulator adb devices
  displayName: 'Run Android tests'
