trigger:
  - master

jobs:
  - job: macOS
    pool:
      vmImage: macOS-latest
      
    steps:
    
      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'
      - script: |
          brew install appium
          ls -lsa /usr/local/Cellar/appium/2.11.3/bin
          appium  driver install xcuitest
          appium  driver install uiautomator2@2.4.5
          brew install libimobiledevice
          brew install carthage
          which appium
        displayName: 'appium'
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: 'Install java.js'
  
      - script: |
          brew install --cask android-commandlinetools
          export ANDROID_HOME=$HOME/Library/Android/sdk
          export APPIUM_HOME=/usr/local/Cellar/appium
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          export PATH=$ANDROID_HOME/emulator:$PATH
          export PATH=$ANDROID_HOME/platform-tools:$PATH
          source ~/.bash_profile
          $ANDROID_HOME/tools/bin/sdkmanager --list
        displayName: 'List already installed Android packages'

      - script: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-30;google_apis;x86_64'
        displayName: 'Install Android image'

      - script: |
          $ANDROID_HOME/emulator/emulator -list-avds
          echo '---'
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test_android_emulator -k 'system-images;android-30;google_apis;x86_64' --force
          echo '---'
          $ANDROID_HOME/emulator/emulator -list-avds
        displayName: 'Create AVD'
        
      - script: |
          $ANDROID_HOME/platform-tools/adb devices
          echo '---'
          nohup $ANDROID_HOME/emulator/emulator -avd test_android_emulator    -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none    > /dev/null 2>&1 & $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          echo '---'
          $ANDROID_HOME/platform-tools/adb devices -l | grep emulator-5554
          $ANDROID_HOME/platform-tools/adb shell getprop
        displayName: 'Start Android emulator'
        
      - script: |
          curl -O https://download.katalon.com/9.6.0/Katalon_Studio_Engine_MacOS-9.6.0.tar.gz
          tar -xzf Katalon_Studio_Engine_MacOS-9.6.0.tar.gz
          cd Katalon_Studio_Engine_MacOS-9.6.0
          sudo mv "Katalon Studio Engine.app" /Applications/
          $ANDROID_HOME/platform-tools/adb devices
          $ANDROID_HOME/platform-tools/adb uninstall io.appium.settings
          $ANDROID_HOME/platform-tools/adb uninstall io.appium.uiautomator2.server
          $ANDROID_HOME/platform-tools/adb uninstall io.appium.uiautomator2.server.test
          $ANDROID_HOME/platform-tools/adb uninstall io.appium.unlock
          export APPIUM_HOME=/usr/local/Cellar/appium/2.11.3
          appium  driver install xcuitest
          appium  driver install uiautomator2@2.4.5
          /Applications/Katalon\ Studio\ Engine.app/Contents/MacOS/katalonc -noSplash -runMode=console  -retry=2 -projectPath="/Users/runner/work/1/s" -testSuitePath="Test Suites/Test_Suite_Mobile" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="f3ab2f6b-d373-4618-b87c-7471b31a5506" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true -appiumDirectory="/usr/local/Cellar/appium/2.11.3/"
        displayName: 'Start Test emulator'
        continueOnError: true

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: $(Pipeline.Workspace)
          artifact: katalon
        continueOnError: true
        
