
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile2'
    tags: |
      $(Build.BuildId)

- script: |
    docker run -t --rm -v "$(pwd)":/tmp/project docker.io/bktpay/katalon-test:$(Build.BuildId) katalonc.sh -projectPath=/tmp/project -noSplash -runMode=console  -retry=0 -testSuitePath="Test Suites/Test_Suite_Mobile" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="554d7f82-ac15-4b60-aab3-739c97658f70" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true 
  displayName: 'Run'

