
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile'
    tags: |
      $(Build.BuildId)

- script: |
    docker run -d --name android_emulator -v $(System.DefaultWorkingDirectory):/workspace docker.io/bktpay/katalon-test:$(Build.BuildId)
  displayName: 'Run Android emulator in Docker container'

- script: |
    docker exec android_emulator adb devices
    docker exec android_emulator adb wait-for-device
    docker exec android_emulator adb shell input keyevent 82
    docker exec android_emulator adb devices
    docker exec android_emulator katalonstudio/katalon/katalonc.sh -noSplash -runMode=console  -retry=0 -testSuitePath="Test Suites/Test_Suite_Mobile" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="554d7f82-ac15-4b60-aab3-739c97658f70" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true -appiumDirectory="/usr/local/lib/node_modules/appium"
  displayName: 'Run Android tests'
