trigger:
  - master

jobs:
  - job: ubuntu
    pool:
      vmImage: ubuntu-latest
      
    steps:
      - task: katalonTask@1
        inputs:
          version: '9.6.0'
          executeArgs: '-noSplash -runMode=console -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Test_Suite_Web" -projectPath="/Users/runner/work/1/s" -browserType="Chrome" --config -webui.autoUpdateDrivers=true -apiKey="f3ab2f6b-d373-4618-b87c-7471b31a5506"'
          
