trigger:
  - master

jobs:
  - job: macOS
    pool:
      vmImage: macOS-latest
      
    steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '20.x'
        displayName: 'Install Node.js'
      - script: |
          npm install -g appium@2.0.0 --unsafe-perm=true --allow-root
          appium driver install xcuites
          npm install -g appium-doctor
          appium-doctor
          brew install libimobiledevice
          brew install carthage
          brew install ios-deploy
          appium driver install uiautomator2
          brew install ios-webkit-debug-proxy
          brew tap kozyrap/libimobiledevice; (brew install --HEAD kozyrap/libimobiledevice/libimobiledevice || arch -arm64 brew install kozyrap/libimobiledevice/libimobiledevice) && brew unlink libimobiledevice && brew link libimobiledevice
        displayName: 'appium'
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: 'Install java.js'
  
      - script: |
          $ANDROID_HOME/tools/bin/sdkmanager --list
        displayName: 'List already installed Android packages'

      - script: |
          echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-33;google_apis;x86_64'
        displayName: 'Install Android image'

      - script: |
          $ANDROID_HOME/emulator/emulator -list-avds
          echo '---'
          echo "no" | $ANDROID_HOME/tools/bin/avdmanager create avd -n test_android_emulator -k 'system-images;android-33;google_apis;x86_64' --force
          echo '---'
          $ANDROID_HOME/emulator/emulator -list-avds
        displayName: 'Create AVD'
      
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'PreInstalled'
        displayName: 'Install java.js'
  
      - script: |
          export KATALON_JAVA_HOME=/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64/Contents/Home/
          export JAVA_HOME=/Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.12-7/x64/Contents/Home/
          $ANDROID_HOME/platform-tools/adb devices
          echo '---'
          nohup $ANDROID_HOME/emulator/emulator -avd test_android_emulator -no-snapshot -no-skin -no-window -no-audio -no-boot-anim -gpu swiftshader_indirect  > /dev/null 2>&1 & $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
          echo '---'
          $ANDROID_HOME/platform-tools/adb devices -l | grep emulator-5554
          $ANDROID_HOME/platform-tools/adb shell getprop
        displayName: 'Start Android emulator'
        

      - script: |
          curl -O https://download.katalon.com/9.0.0/Katalon_Studio_Engine_MacOS-9.0.0.tar.gz
          tar -xzvf Katalon_Studio_Engine_MacOS-9.0.0.tar.gz
          ls
          mv Katalon_Studio_Engine /Applications/Katalon_Studio_Engine
          ls
          cd  /Applications/Katalon_Studio_Engine
          chmod +x katalonc
          ./katalonc -noSplash -runMode=console  -retry=0 -projectPath="/Users/runner/work/1/s" -testSuitePath="Test Suites/Test_Suite_Mobile" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="554d7f82-ac15-4b60-aab3-739c97658f70" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true  -webui.autoUpdateDrivers=true -appiumDirectory="/Users/runner/hostedtoolcache/node/20.16.0/x64/lib/node_modules/appium"
        displayName: 'Start Test emulator'
