
trigger:
- master

pool:
  vmImage: 'ubuntu-21.04'

steps:
- checkout: self

- task: Docker@2
  displayName: 'Build Docker image'
  inputs:
    repository: '$(Build.Repository.Name)'
    command: 'build'
    Dockerfile: '**/dockerfile2'
    tags: |
      $(Build.BuildId)
- script: |
    docker run -t --rm -v $(pwd):/tmp/project docker.io/bktpay/katalon-test:$(Build.BuildId) katalonc.sh -noSplash -runMode=console -projectPath=/tmp/project -testSuitePath="Test Suites/Test_Suite_Mobile" -browserType="Android" -deviceId="emulator-5554" -executionProfile="default" -apiKey="f40e6675-f266-4c69-a67b-1637d512d361" -appiumDirectory="/usr/local/lib/node_modules/appium"
 
  displayName: 'Run Android emulator in Docker container'
- task: PublishPipelineArtifact@1
  condition: succeededOrFailed() 
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
    
