<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Reconciliation</name>
   <tag></tag>
   <elementGuidId>790246bd-3252-4fd9-954d-9264a2b1788a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div:nth-of-type(3) > li > a > div.sidebar_menuItem__3mWxl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/aside/ul/div[3]/li/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=list >> internal:role=link[name=&quot;Reconciliation&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4635ef1f-57e2-4a0b-8298-4d884710b578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar_menuItem__3mWxl</value>
      <webElementGuid>d3340123-f9e8-4a63-8fdd-8d76323951ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>32e5e872-1aa6-4493-bfe4-9515ea072476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reconciliation</value>
      <webElementGuid>1e4cafe5-2211-4bd7-9c91-770484d91c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout__tZtl7&quot;]/aside[@class=&quot;sidebar_sidebar___sE6K&quot;]/ul[@class=&quot;sidebar_menu__2b3Rz&quot;]/div[3]/li[1]/a[1]/div[@class=&quot;sidebar_menuItem__3mWxl&quot;]</value>
      <webElementGuid>bf379fef-a3ab-4e75-a10f-7b8a4e601a22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/aside/ul/div[3]/li/a/div</value>
      <webElementGuid>643a530e-d0ed-41e9-ac5a-e521aa27fd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/following::div[2]</value>
      <webElementGuid>fe2423b4-c253-47d5-89d7-18a2ca685d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual'])[1]/following::div[4]</value>
      <webElementGuid>315573a8-4d20-42b1-84d3-6e724e2a7498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASBS Transactions'])[1]/preceding::div[1]</value>
      <webElementGuid>50b0a1f2-e646-4d90-9816-d38123ede417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fraud Transactions'])[1]/preceding::div[3]</value>
      <webElementGuid>6bb66e8f-caf6-42d7-8f29-c30acaa8bb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Reconciliation']/parent::*</value>
      <webElementGuid>d3fdc1d8-7b88-42d9-8536-835f0913aeb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/li/a/div</value>
      <webElementGuid>4d1b6ac3-f151-433e-9e5f-c997bad6a1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Reconciliation' or . = 'Reconciliation')]</value>
      <webElementGuid>6f3fa589-728f-4987-aa15-f8e64a433298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
