<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Individual</name>
   <tag></tag>
   <elementGuidId>7020f195-64d8-410a-be85-6915eb10d84a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/aside/ul/div[2]/li/ul/div/li/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.sidebar_childMenu__szekR > div > li > a > div.sidebar_menuItem__3mWxl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Individual&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>103cf54f-845e-452c-ba15-0224d9e2fa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebar_menuItem__3mWxl</value>
      <webElementGuid>7f214ccc-a2b0-48cd-b7c8-f0fc0f4161fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-active</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1498e5d7-84ef-4c62-af56-7aaf5cafe3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Individual</value>
      <webElementGuid>cf2d582b-784b-4352-b9ca-a42de764f6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout_layout__tZtl7&quot;]/aside[@class=&quot;sidebar_sidebar___sE6K&quot;]/ul[@class=&quot;sidebar_menu__2b3Rz&quot;]/div[2]/li[1]/ul[@class=&quot;sidebar_childMenu__szekR&quot;]/div[1]/li[1]/a[1]/div[@class=&quot;sidebar_menuItem__3mWxl&quot;]</value>
      <webElementGuid>e0d4eb55-9e8c-4cff-9440-7c8d2bd4aa3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/aside/ul/div[2]/li/ul/div/li/a/div</value>
      <webElementGuid>37819128-d52e-4dbf-a592-530bb2543de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Management'])[1]/following::div[2]</value>
      <webElementGuid>ea60433b-34a2-4808-9d75-89cb51923e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::div[4]</value>
      <webElementGuid>ee059296-3909-44b8-b07d-55ac1cee3bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business'])[1]/preceding::div[1]</value>
      <webElementGuid>8b37617f-92f5-45e1-ada0-c151d4517930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reconciliation'])[1]/preceding::div[3]</value>
      <webElementGuid>9e9760c1-5283-4f47-b7c1-771eecad16c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Individual']/parent::*</value>
      <webElementGuid>e29cf874-6409-4872-a483-a5385b17e4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/div/li/a/div</value>
      <webElementGuid>74b567e8-e478-4efb-98d6-903b111da9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Individual' or . = 'Individual')]</value>
      <webElementGuid>26a38faf-2e6c-4448-b814-f6f6606c7d55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
